pure_pursuit_node:
  ros__parameters:
    lookahead_distance: 1.4
    curvature_gain: 0.6
    #Left
    lane1_file_path: "/config/wp-2025-03-08-01-27-47_first_complete_loop.csv"
    #center
    lane2_file_path: "/config/wp-2025-03-08-01-27-47_first_complete_loop.csv"
    #right
    lane3_file_path: "/config/wp-2025-03-08-01-27-47_first_complete_loop.csv"
    max_speed: 6.0
    min_speed: 2.5
    max_steering_angle: 0.7853981633974483  # np.pi / 4
    sim: True # set to False for real car 
    map_sim: True

pure_pursuit_node_d:
  ros__parameters:
    lookahead_distance: 1.5
    curvature_gain: 0.5
    waypoint_file_path_in_package: "/config/wp-2025-03-08-01-27-47_first_complete_loop.csv"
    # waypoint_file_path_in_package: "/config/wp-2025-03-19-00-25-36.csv"
    max_speed: 7.0
    min_speed: 2.5
    max_steering_angle: 0.7853981633974483  # np.pi / 4
    sim: True # set to False for real car will handle the next 2 params odom_topic and drive_topic also automatically
    odom_topic: "/ego_racecar/odom" # "/opp_racecar/odom" The parameter is only used in sim mode as otherwise subscribe to the topic "pf/pose/odom" with sim False is programmed
    drive_topic: "/drive" # "/opp_drive" The parameter is only used in sim mode as otherwise publish to the topic "/drive" with sim False is programmed
    map_sim: True
    is_debug: False